# global built-in configuration
fix                   = false
show-fixes            = true
line-length           = 88
indent-width          = 4
exclude               = [".venv"]
# how ruff is going to format code
[format]
quote-style           = "double"
indent-style          = "space"
line-ending           = "cr-lf"
docstring-code-format = true
# what kind of lints is it going to apply
[lint]
select                = ["ALL"]
[pycodestyle]
max-line-length       = 120